DEP-11 -- Fix error logic find_dependabot

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -54,6 +54,19 @@ runs:
 # Verify some properties of the PR and also check that the target branch is enabled for auto-merging
 # For instance, by default we do not allow to automerge to "master"
 
+    - name: Find dependabot config
+      id: find_config
+      shell: bash
+      run: |
+        if [ -f ./.github/dependabot.yaml ]; then
+          echo "::set-output name=ext::yaml"
+        elif [ -f ./.github/dependabot.yml ]; then
+          echo "::set-output name=ext::yml"
+        else
+          echo "::error::Cannot find dependabot config"
+          exit 1
+        fi
+
     - name: Shoud merge the PR?
       id: shouldmergepr
       if: >- # Check if it's dependabot
@@ -66,7 +79,7 @@ runs:
       env:
         DISABLED_TARGETS: ${{inputs.disabled_pr_targets}}
         BASE_REF: ${{github.base_ref}}
-        DEPCONF: ./.github/dependabot.${{steps.find_dependabot.outputs.ext}}
+        DEPCONF: ./.github/dependabot.${{steps.find_config.outputs.ext}}
         REF_NAME: ${{github.ref_name}}
       run: | # Check if the branch is enabled
         readarray -d , -t MERGEREFS <<< "$DISABLED_TARGETS"
